import json
import logging
import math
import mimetypes
import os
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta
from functools import cached_property
from pathlib import Path
from typing import Any, Protocol

import requests

logger = logging.getLogger(__name__)

# S3 multipart minimum part size (5 MiB) applies to every part except the last.
PART_SIZE = 5 * 1024 * 1024
DEFAULT_MIMETYPE = "application/octet-stream"
TOKEN_REFRESH_BUFFER_SECONDS = 30

# (connect, read) timeouts. Read on PART PUT capped at 15 min because the
# presigned URL is generated by Lambda and its lifetime can't exceed Lambda's
# 15-minute max — a longer wait can't recover.
TOKEN_TIMEOUT = (30, 60)
API_TIMEOUT = (30, 120)
PART_PUT_TIMEOUT = (30, 900)

FILE_TYPE_OPEN = "OpenFile"
FILE_TYPE_INTERNAL = "InternalFile"

# Every File artifact type ends in "File" (OpenFile, InternalFile,
# PendingOpenFile, ...) whereas AssociatedLink does not, so the suffix
# distinguishes uploaded files from links in associatedArtifacts.
FILE_ARTIFACT_TYPE_SUFFIX = "File"

PUBLISHER_VERSION_PUBLISHED = "PublishedVersion"
PUBLISHER_VERSION_ACCEPTED = "AcceptedVersion"

EXTERNAL_COMPLETE_TYPE = "ExternalCompleteUpload"

ASSOCIATED_LINK_TYPE = "AssociatedLink"
RELATION_SAME_AS = "sameAs"
UPDATE_PUBLICATION_TYPE = "Publication"
ROUND_TRIP_FIELDS = (
    "entityDescription",
    "projects",
    "subjects",
    "fundings",
    "rightsHolder",
)

# HTTP header read by RequestUtil -> ThirdPartySystem.fromValue. Drives the
# importSource on the resource log entries (FileUploadedEvent/PublishedResourceEvent).
# Missing/unknown value falls back to Source.OTHER, so we must set it to "DLR".
SYSTEM_HEADER = "System"
SYSTEM_DLR = "DLR"

API_DOMAIN_PARAMETER = "/NVA/ApiDomain"


@dataclass
class ExternalClientToken:
    """Cognito client-credentials token for a single external client key.

    Built from an external-client key file (clientId / clientSecret / tokenUrl).
    Ownership of uploaded files is derived from which external client performs
    the upload, so each key maps to one institution/customer (customerUri).
    """

    client_id: str
    client_secret: str
    token_url: str
    customer_uri: str | None = None
    client_name: str | None = None
    _token: str | None = field(default=None, init=False, repr=False)
    _expires_at: datetime | None = field(default=None, init=False, repr=False)

    @classmethod
    def from_key_file(cls, path: str | Path) -> "ExternalClientToken":
        key = json.loads(Path(path).read_text())
        return cls(
            client_id=key["clientId"],
            client_secret=key["clientSecret"],
            token_url=key["tokenUrl"],
            customer_uri=key.get("customerUri"),
            client_name=key.get("clientName"),
        )

    def bearer(self) -> str:
        if self._token is None or self._is_expired():
            self._refresh()
        assert self._token is not None
        return self._token

    def _refresh(self) -> None:
        response = requests.post(
            self.token_url,
            headers={"Content-Type": "application/x-www-form-urlencoded"},
            data={
                "grant_type": "client_credentials",
                "client_id": self.client_id,
                "client_secret": self.client_secret,
            },
            timeout=TOKEN_TIMEOUT,
        )
        response.raise_for_status()
        body = response.json()
        self._token = body["access_token"]
        self._expires_at = datetime.now() + timedelta(seconds=body["expires_in"])

    def _is_expired(self) -> bool:
        if self._expires_at is None:
            return True
        return datetime.now() > self._expires_at - timedelta(
            seconds=TOKEN_REFRESH_BUFFER_SECONDS
        )


class FileSource(Protocol):
    @property
    def filename(self) -> str: ...

    @property
    def mimetype(self) -> str: ...

    @property
    def size(self) -> int: ...

    def read_part(self, part_number: int, part_size: int) -> bytes: ...


@dataclass
class LocalFileSource:
    path: str
    mimetype_override: str | None = None

    @property
    def filename(self) -> str:
        return os.path.basename(self.path)

    @property
    def mimetype(self) -> str:
        if self.mimetype_override:
            return self.mimetype_override
        guessed, _ = mimetypes.guess_type(self.path)
        return guessed or DEFAULT_MIMETYPE

    @property
    def size(self) -> int:
        return os.path.getsize(self.path)

    def read_part(self, part_number: int, part_size: int) -> bytes:
        with open(self.path, "rb") as file:
            file.seek((part_number - 1) * part_size)
            return file.read(part_size)


@dataclass
class S3ObjectSource:
    s3_client: Any
    bucket: str
    key: str
    filename_override: str | None = None
    mimetype_override: str | None = None
    size_override: int | None = None

    @cached_property
    def _head(self) -> dict:
        return self.s3_client.head_object(Bucket=self.bucket, Key=self.key)

    @property
    def filename(self) -> str:
        if self.filename_override:
            return self.filename_override
        return os.path.basename(self.key)

    @property
    def mimetype(self) -> str:
        if self.mimetype_override:
            return self.mimetype_override
        content_type = self._head.get("ContentType")
        if content_type and content_type != "binary/octet-stream":
            return content_type
        guessed, _ = mimetypes.guess_type(self.key)
        return guessed or DEFAULT_MIMETYPE

    @property
    def size(self) -> int:
        if self.size_override is not None:
            return self.size_override
        return self._head["ContentLength"]

    def read_part(self, part_number: int, part_size: int) -> bytes:
        start = (part_number - 1) * part_size
        end = min(start + part_size, self.size) - 1
        response = self.s3_client.get_object(
            Bucket=self.bucket, Key=self.key, Range=f"bytes={start}-{end}"
        )
        return response["Body"].read()


@dataclass
class FileUploadApiService:
    api_domain: str
    token: ExternalClientToken
    system: str = SYSTEM_DLR

    def upload(
        self,
        publication_identifier: str,
        source: FileSource,
        *,
        file_type: str = FILE_TYPE_OPEN,
        license: str | None = None,
        publisher_version: str | None = None,
        embargo_date: str | None = None,
    ) -> dict:
        upload_id, key = self._create(publication_identifier, source)
        logger.info(
            "Started upload %s for %s (key %s, %d bytes)",
            upload_id,
            publication_identifier,
            key,
            source.size,
        )
        parts = self._upload_parts(publication_identifier, source, upload_id, key)
        return self._complete(
            publication_identifier,
            upload_id,
            key,
            parts,
            file_type,
            license,
            publisher_version,
            embargo_date,
        )

    def _create(
        self, publication_identifier: str, source: FileSource
    ) -> tuple[str, str]:
        body = self._post(
            publication_identifier,
            "create",
            {
                "filename": source.filename,
                "size": str(source.size),
                "mimetype": source.mimetype,
            },
        )
        return body["uploadId"], body["key"]

    def _upload_parts(
        self,
        publication_identifier: str,
        source: FileSource,
        upload_id: str,
        key: str,
    ) -> list[dict]:
        num_parts = max(1, math.ceil(source.size / PART_SIZE))
        parts = []
        for part_number in range(1, num_parts + 1):
            chunk = source.read_part(part_number, PART_SIZE)
            etag = self._upload_part(
                publication_identifier, upload_id, key, part_number, chunk
            )
            parts.append({"partNumber": part_number, "etag": etag})
            logger.info("  part %d/%d uploaded (etag %s)", part_number, num_parts, etag)
        return parts

    def _upload_part(
        self,
        publication_identifier: str,
        upload_id: str,
        key: str,
        part_number: int,
        chunk: bytes,
    ) -> str:
        prepare_body = self._post(
            publication_identifier,
            "prepare",
            {"uploadId": upload_id, "key": key, "number": str(part_number)},
        )
        presigned_url = prepare_body["url"]
        response = requests.put(presigned_url, data=chunk, timeout=PART_PUT_TIMEOUT)
        _raise_for_status_with_body(response)
        return response.headers["ETag"].strip('"')

    def _complete(
        self,
        publication_identifier: str,
        upload_id: str,
        key: str,
        parts: list[dict],
        file_type: str,
        license: str | None,
        publisher_version: str | None,
        embargo_date: str | None,
    ) -> dict:
        body = {
            "type": EXTERNAL_COMPLETE_TYPE,
            "uploadId": upload_id,
            "key": key,
            "parts": parts,
            "fileType": file_type,
        }
        if license is not None:
            body["license"] = license
        if publisher_version is not None:
            body["publisherVersion"] = publisher_version
        if embargo_date is not None:
            body["embargoDate"] = embargo_date
        return self._post(publication_identifier, "complete", body)

    def create_publication(self, title: str) -> dict:
        """Create a minimal DLR-shaped draft via the third-party endpoint.

        Mirrors the shape of real DLR-imported resources (OtherPresentation with
        Event publicationContext + one Contributor) so the NVA frontend can
        actually render the registration page. Without publicationContext or
        contributors the public registration view crashes client-side.
        """
        url = f"https://{self.api_domain}/publication"
        today = date.today()
        body = {
            "type": "Publication",
            "entityDescription": {
                "type": "EntityDescription",
                "mainTitle": title,
                "publicationDate": {
                    "type": "PublicationDate",
                    "year": str(today.year),
                    "month": f"{today.month:02d}",
                    "day": f"{today.day:02d}",
                },
                "contributors": [
                    {
                        "type": "Contributor",
                        "identity": {
                            "type": "Identity",
                            "name": "DLR smoke-test",
                        },
                        "role": {"type": "Creator"},
                        "sequence": 1,
                        "correspondingAuthor": False,
                    }
                ],
                "reference": {
                    "type": "Reference",
                    "publicationContext": {
                        "type": "Event",
                        "name": "dlr-smoke-test",
                        "agent": {
                            "type": "UnconfirmedOrganization",
                            "name": "dlr",
                        },
                        "time": {
                            "type": "Period",
                            "from": f"{today.isoformat()}T00:00:00.000Z",
                        },
                    },
                    "publicationInstance": {
                        "type": "OtherPresentation",
                        "pages": {"type": "NullPages"},
                    },
                },
            },
        }
        response = requests.post(
            url, headers=self._headers(), json=body, timeout=API_TIMEOUT
        )
        _raise_for_status_with_body(response)
        publication = response.json()
        logger.info("Created publication %s", publication.get("identifier"))
        return publication

    def get_publication(self, publication_identifier: str) -> dict:
        url = f"https://{self.api_domain}/publication/{publication_identifier}"
        response = requests.get(url, headers=self._headers(), timeout=API_TIMEOUT)
        _raise_for_status_with_body(response)
        return response.json()

    def existing_file_signatures(
        self, publication_identifier: str
    ) -> set[tuple[str, int]]:
        """Return {(name, size)} for File artifacts already on the publication.

        Lets callers make uploads idempotent against NVA itself: a file whose
        (name, size) already exists in associatedArtifacts can be skipped, even
        when the local state file is missing.
        """
        publication = self.get_publication(publication_identifier)
        signatures: set[tuple[str, int]] = set()
        for artifact in publication.get("associatedArtifacts") or []:
            if not str(artifact.get("type", "")).endswith(FILE_ARTIFACT_TYPE_SUFFIX):
                continue
            name = artifact.get("name")
            size = artifact.get("size")
            if name is not None and size is not None:
                signatures.add((name, int(size)))
        return signatures

    def update_publication(
        self, publication_identifier: str, publication: dict
    ) -> dict:
        url = f"https://{self.api_domain}/publication/{publication_identifier}"
        response = requests.put(
            url, headers=self._headers(), json=publication, timeout=API_TIMEOUT
        )
        _raise_for_status_with_body(response)
        return response.json()

    def add_associated_links(
        self,
        publication_identifier: str,
        urls: list[str],
        relation: str = RELATION_SAME_AS,
    ) -> tuple[int, int]:
        """GET the publication, append AssociatedLink artifacts for URLs not
        already linked, PUT it back as an UpdatePublicationRequest.

        Returns (added_count, skipped_count). Skipped = URL already linked as an
        AssociatedLink. Idempotent: re-running is a no-op.

        Round-trips the full associatedArtifacts list (including uploaded files)
        plus entityDescription, projects, subjects, fundings, rightsHolder,
        because UpdatePublicationRequest overwrites every field it accepts;
        omitting associatedArtifacts would delete the uploaded files.
        """
        publication = self.get_publication(publication_identifier)
        artifacts = list(publication.get("associatedArtifacts") or [])
        existing_link_ids = {
            artifact.get("id")
            for artifact in artifacts
            if artifact.get("type") == ASSOCIATED_LINK_TYPE
        }
        new_links = [
            {
                "type": ASSOCIATED_LINK_TYPE,
                "id": url,
                "relation": relation,
            }
            for url in urls
            if url and url not in existing_link_ids
        ]
        if not new_links:
            return (0, len(urls))
        body = {
            "type": UPDATE_PUBLICATION_TYPE,
            "identifier": publication_identifier,
            "associatedArtifacts": artifacts + new_links,
        }
        for field_name in ROUND_TRIP_FIELDS:
            if field_name in publication:
                body[field_name] = publication[field_name]
        updated = self.update_publication(publication_identifier, body)
        persisted_link_ids = {
            artifact.get("id")
            for artifact in (updated.get("associatedArtifacts") or [])
            if artifact.get("type") == ASSOCIATED_LINK_TYPE
        }
        intended_ids = {link["id"] for link in new_links}
        missing = intended_ids - persisted_link_ids
        if missing:
            raise RuntimeError(
                f"PUT returned 200 but the following AssociatedLink URLs "
                f"are not in the response (NVA silently dropped them): "
                f"{sorted(missing)}"
            )
        return (len(new_links), len(urls) - len(new_links))

    def publish(self, publication_identifier: str) -> None:
        """Publish a draft directly (no ticket). Idempotent: 409/already-published is ok.

        Sends System: DLR so the PublishedResourceEvent log entry gets source DLR.
        """
        url = f"https://{self.api_domain}/publication/{publication_identifier}/publish"
        response = requests.post(url, headers=self._headers(), timeout=API_TIMEOUT)
        if response.status_code == 409:
            logger.info("%s already published", publication_identifier)
            return
        _raise_for_status_with_body(response)
        logger.info("Published %s (%d)", publication_identifier, response.status_code)

    def delete_publication(self, publication_identifier: str) -> None:
        """Delete a DRAFT publication and its pending files.

        NVA only allows deleting resources in status DRAFT; a published resource
        is rejected (must be unpublished first). The response body carries the
        reason on rejection.
        """
        url = f"https://{self.api_domain}/publication/{publication_identifier}"
        response = requests.delete(url, headers=self._headers(), timeout=API_TIMEOUT)
        _raise_for_status_with_body(response)
        logger.info("Deleted %s (%d)", publication_identifier, response.status_code)

    def _post(self, publication_identifier: str, action: str, body: dict) -> dict:
        url = (
            f"https://{self.api_domain}/publication/"
            f"{publication_identifier}/file-upload/{action}"
        )
        response = requests.post(
            url, headers=self._headers(), json=body, timeout=API_TIMEOUT
        )
        _raise_for_status_with_body(response)
        return response.json()

    def _headers(self) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {self.token.bearer()}",
            "Content-Type": "application/json",
            "Accept": "application/json",
            SYSTEM_HEADER: self.system,
        }


def resolve_api_domain(session: Any) -> str:
    response = session.client("ssm").get_parameter(Name=API_DOMAIN_PARAMETER)
    return response["Parameter"]["Value"]


def _raise_for_status_with_body(response: requests.Response) -> None:
    if response.ok:
        return
    snippet = (response.text or "").strip()[:1000]
    raise requests.HTTPError(
        f"{response.status_code} {response.reason} for {response.url}: {snippet}",
        response=response,
    )
